T315Y24/Assets/Script.meta
T315Y24/Assets/Script/CodingRule.cs
T315Y24/Assets/Script/CodingRule.cs.meta

コーディング規約を記述

---

T315Y24/Packages/manifest.json
T315Y24/Packages/packages-lock.json
T315Y24/ProjectSettings/PackageManagerSettings.asset

GitForUnity適用

---

T315Y24/Assets/Script/CodingRule.cs
T315Y24/Assets/Script/Enemy/EnemyNormal.cs

コーディング規約を修正。
ついでにスクリプト上にあった無駄な関数を除去

コーディング規約修正

---

T315Y24/Assets/Fonts.meta
T315Y24/Assets/Fonts/NotoSerifJP-Regular SDF.asset
T315Y24/Assets/Fonts/NotoSerifJP-Regular SDF.asset.meta
T315Y24/Assets/Fonts/NotoSerifJP-Regular.otf
T315Y24/Assets/Fonts/NotoSerifJP-Regular.otf.meta
T315Y24/Assets/Scenes/ProtoStage.unity
T315Y24/Assets/Script/Enemy/Types/CEnemy.cs
T315Y24/Assets/Script/Enemy/Types/EnemyNormal.cs
T315Y24/Assets/Script/UI/EnemyDeathCounter.cs
T315Y24/Assets/Script/UI/EnemyDeathCounter.cs.meta
T315Y24/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset

討伐数追加＆フォント追加

---

T315Y24/Assets/Scenes/ProtoStage.unity

Timerの位置調整

---

T315Y24/Assets/Prefabs/Proto/Zombie_with_Face.prefab
T315Y24/Assets/Scenes/ProtoStage.unity
T315Y24/Assets/Script/Enemy/NavigationPlayer.cs
T315Y24/Assets/Script/Enemy/Types/CEnemy.cs
T315Y24/Assets/Script/Enemy/Types/EnemyNormal.cs
T315Y24/Assets/Script/Traps/ArrowRain/Arrow.cs
T315Y24/Assets/Script/Traps/ArrowRain/ArrowRain.cs
T315Y24/Assets/Script/Traps/Explosion/Explosion.cs
T315Y24/Assets/Script/UI/EnemyDeathCounter.cs
T315Y24/Assets/Script/UI/TimeManager.cs

コメントの追加、謎の改行を削除、ヒエラルキーにあるものを名前変更

コメント追加しました

---

T315Y24/Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
T315Y24/Assets/Prefabs/Proto/Zombie_with_Face.prefab
T315Y24/Assets/Scenes/ProtoStage.unity
T315Y24/Assets/Script/GameEndManager/GameClear.cs
T315Y24/Assets/Script/Phase/PhaseManager.cs

フェーズ用に仕様変更

---

T315Y24/Assets/Scenes/ProtoStage.unity
T315Y24/Assets/Script/GeneralPurpose/Enemy/EnemyList.cs
T315Y24/Assets/Script/Phase/PhaseManager.cs
T315Y24/Assets/Script/Player/PlayerDashInterval.cs
T315Y24/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
T315Y24/ProjectSettings/NavMeshAreas.asset

敵の出現率を修正。
フェーズがいくつなのかを表示。
プレイヤーのダッシュクールダウン表記の脱字修正。

敵確率修正・フェーズ表示

---

T315Y24/Assets/Scenes/Stage01.unity

シーン変更部上げ忘れ

---

T315Y24/Assets/Materials/SceneTransition.mat
T315Y24/Assets/Prefabs/Proto/Mine.prefab
T315Y24/Assets/Prefabs/Proto/RemoteBomb.prefab
T315Y24/Assets/Scenes/GameoverScene.unity
T315Y24/Assets/Scenes/ResultScene.unity
T315Y24/Assets/Scenes/SelectScene.unity
T315Y24/Assets/Scenes/Stage01.unity
T315Y24/Assets/Scenes/TitleScene.unity
T315Y24/Assets/Script/Scene/ChangeScene.cs
T315Y24/Assets/Script/Traps/Mine/Mine.cs
T315Y24/Assets/Script/Traps/RemoteBomb.cs
T315Y24/Assets/Script/Traps/Trap.cs
T315Y24/Assets/Script/Traps/TrapSelect.cs
T315Y24/ProjectSettings/InputManager.asset

コストUIは後で変更予定。
Mapにcollision付けないとどこでも置けるようになってしまいます。。。

罠のコスト追加、罠設置判定、コントローラー対応

---

T315Y24/Assets/Scenes/Stage01.unity
T315Y24/Assets/Script/Player/PlayerScript.cs
T315Y24/Assets/Script/Traps/Trap.cs
T315Y24/Assets/Script/Traps/TrapSelect.cs
T315Y24/ProjectSettings/InputManager.asset

Dashコントローラー対応、罠コストを表示

---

T315Y24/Assets/Script/CodingRule.cs

・インスペクタでの見た目を意識した記述指示追加
・メンバーでない変数の書き方変更

コーディング規約更新

---

T315Y24/Assets/Prefabs/Traps/Explosive_Barrel.prefab
T315Y24/Assets/Prefabs/Traps/Landmine.prefab
T315Y24/Assets/Scenes/ResultScene.unity
T315Y24/Assets/Script/Traps/Trap.cs

罠透明化とリザルトのテキストの位置調整

---

T315Y24/Assets/Materials/m_DissolveTransparent.mat
T315Y24/Assets/Scenes/GameoverScene.unity
T315Y24/Assets/Scenes/ResultScene.unity
T315Y24/Assets/Scenes/Stage01.unity
T315Y24/Assets/Scenes/TitleScene.unity
T315Y24/Assets/Script/GameEndManager/GameClear.cs
T315Y24/Assets/Script/GameEndManager/GameOver.cs
T315Y24/Assets/Script/Scene/ChangeScene.cs

ChangeTransition

---

T315Y24/Assets/AddressableAssetsData/AddressableAssetSettings.asset
T315Y24/Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
T315Y24/Assets/Animation/Zombie.controller
T315Y24/Assets/Animation/Zombie.controller.meta
T315Y24/Assets/Animation/Zombie.meta
T315Y24/Assets/Animation/Zombie/Zombie_Attack03.fbx
T315Y24/Assets/Animation/Zombie/Zombie_Attack03.fbx.meta
T315Y24/Assets/Animation/Zombie/Zombie_Power_Attack02.fbx
T315Y24/Assets/Animation/Zombie/Zombie_Power_Attack02.fbx.meta
T315Y24/Assets/Animation/Zombie/Zombie_Power_Run02.fbx
T315Y24/Assets/Animation/Zombie/Zombie_Power_Run02.fbx.meta
T315Y24/Assets/Animation/Zombie/Zombie_Run03.fbx
T315Y24/Assets/Animation/Zombie/Zombie_Run03.fbx.meta
T315Y24/Assets/Animation/Zombie_Power.controller
T315Y24/Assets/Animation/Zombie_Power.controller.meta
T315Y24/Assets/FencesPack/Materials/WoodWhite.mat
T315Y24/Assets/Materials/m_DissolveTransparent.mat
T315Y24/Assets/Models/NewZombieCharacterModel+Textures/Zombie_Model.fbx.meta
T315Y24/Assets/Prefabs/Player.prefab
T315Y24/Assets/Prefabs/PlayerModel.prefab
T315Y24/Assets/Prefabs/Proto/Zombie_Model.prefab
T315Y24/Assets/Prefabs/Proto/Zombie_Normal.prefab
T315Y24/Assets/Prefabs/Proto/Zombie_Normal.prefab.meta
T315Y24/Assets/Prefabs/Proto/Zombie_Power.prefab
T315Y24/Assets/Prefabs/Proto/Zombie_Power.prefab.meta
T315Y24/Assets/Prefabs/Proto/Zombie_with_Face.prefab
T315Y24/Assets/Scenes/Stage01.unity
T315Y24/Assets/Script/Enemy/Types/EnemyAttach.cs

敵のアニメーション追加

---

T315Y24/Assets/Script/MapObject/Transparent.cs

FixTransparent

---

T315Y24/Assets/DefaultVolumeProfile.asset
T315Y24/Assets/Materials/m_DissolveTransparent.mat
T315Y24/Assets/Scenes/Stage01.unity
T315Y24/ProjectSettings/GraphicsSettings.asset

TransparentFix

---

T315Y24/Assets/Prefabs/Singleton/Tutorial.prefab
T315Y24/Assets/Script/Tutorial.cs

チュートリアルの背景

---

T315Y24/Assets/Prefabs/Singleton/Tutorial.prefab
T315Y24/Assets/Script/GameEndManager/FeatureGameOver.cs
T315Y24/Assets/Script/GameEndManager/FeatureGameOver.cs.meta
T315Y24/Assets/Script/GameEndManager/GameOver.cs
T315Y24/Assets/Script/Player/PlayerScript.cs
T315Y24/Assets/Script/Traps/TrapSelect.cs
T315Y24/Assets/Script/Tutorial.cs

ゲームオーバー＆チュウトリアル中の操作を不能

---

T315Y24/Assets/Animation/Player.controller
T315Y24/Assets/Animation/Player/Idle.fbx.meta
T315Y24/Assets/Animation/Player/PlayerDeath_v4.fbx
T315Y24/Assets/Animation/Player/PlayerDeath_v4.fbx.meta
T315Y24/Assets/Animation/Player/Player_Dodge02.fbx.meta
T315Y24/Assets/Animation/Player/Player_Run02.fbx.meta
T315Y24/Assets/Script/Player/PlayerScript.cs

プレイヤー死亡時モーション実装

---

T315Y24/Assets/Animation/Zombie.controller
T315Y24/Assets/Animation/Zombie/Zombie_Idle.fbx
T315Y24/Assets/Animation/Zombie/Zombie_Idle.fbx.meta
T315Y24/Assets/Animation/Zombie/Zombie_Power_Idle.fbx
T315Y24/Assets/Animation/Zombie/Zombie_Power_Idle.fbx.meta
T315Y24/Assets/Animation/Zombie_Power.controller
T315Y24/Assets/Materials/m_DissolveTransparent.mat
T315Y24/Assets/Script/Enemy/Types/EnemyAttach.cs

ゾンビの待機モーション追加

---

T315Y24/Assets/Prefabs/Singleton/Tutorial.prefab
T315Y24/Assets/Script/Traps/TrapSelect.cs
T315Y24/Assets/Script/Tutorial.cs

チュートリアルUI基盤

---

T315Y24/Assets/Materials/m_DissolveTransparent.mat
T315Y24/Assets/Script/GameEndManager/GameOver.cs
T315Y24/Assets/Script/UI/CostUI.cs

gameover時にコスト停止させました
